// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynapauakxtzwyhdreeha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYXBhdWFreHR6d3loZHJlZWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjY1MDQsImV4cCI6MjA2NTg0MjUwNH0.Gmfxi1s8iTOfA3Z4m7JN7EHxzY5xHjNg9lSLjoVSATM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);